;;; fzfa-replay.el --- Persisted replay for `fzfa' sessions -*- lexical-binding: t; -*-

;; Copyright (C) 2026 James Nguyen

;; Author: James Nguyen <james@jojojames.com>
;; Version: 1.0
;; Package-Requires: ((emacs "29.1"))
;; Homepage: https://github.com/jojojames/fzfa
;; Assisted-by: Claude:claude-opus-4-7
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Persists `fzfa--sessions' to disk so `fzfa-replay'-class commands
;; can reach past Emacs lifetimes.  Modeled on `recentf':
;;
;;   `fzfa-replay-mode'  Global minor mode.  Enabling it loads the
;;                       on-disk session list, installs an idle
;;                       auto-save timer, and registers a final
;;                       save on `kill-emacs-hook'.
;;
;; The in-memory ring `fzfa--sessions' is captured by `fzfa--read'
;; regardless of this extension — replay-from-memory works without
;; loading anything.  This file adds the disk round-trip.

;;; Code:

(require 'fzfa)

;;; Customization

(defgroup fzfa-replay nil
  "Persisted replay for `fzfa' sessions."
  :group 'fzfa)

(defcustom fzfa-replay-file
  (locate-user-emacs-file ".fzfa-replay")
  "File where `fzfa-replay-mode' persists the session list."
  :type 'file
  :group 'fzfa-replay)

(defcustom fzfa-replay-max-saved-items 20
  "Maximum number of sessions kept in `fzfa-replay-file'.

Independent of `fzfa-sessions-max', which caps the in-memory ring.
The on-disk ring is typically larger — it's the retention horizon
across Emacs lifetimes; the in-memory ring is the recent-activity
window."
  :type 'natnum
  :group 'fzfa-replay)

(defcustom fzfa-replay-save-file-modes #o600
  "Permission bits set on `fzfa-replay-file' after writing.
Nil leaves modes alone.  Sessions can contain typed queries and
buffer / file paths — owner-only is the safe default."
  :type '(choice integer (const nil))
  :group 'fzfa-replay)

(defcustom fzfa-replay-auto-save-interval 300
  "Seconds of idle time between background saves of the session list.
A non-positive value disables periodic saving (`kill-emacs-hook'
still runs the final save)."
  :type 'number
  :group 'fzfa-replay)

;;; State

(defvar fzfa-replay-auto-save-timer nil
  "Idle timer installed by `fzfa-replay-mode' for periodic saves.
Nil when the mode is disabled.")

(defvar fzfa-replay--persisted-sessions nil
  "On-disk session list, loaded by `fzfa-replay-load-list'.

Kept separate from `fzfa--sessions' so:
- Disk reads never block the in-memory picker.
- The two rings trim independently (recent activity vs.
  retention horizon).
- The pickers can present them as distinct sources without
  invented merging rules.

`fzfa-replay-from-file' (Phase B-3) picks over this variable;
`fzfa-replay-any' (Phase B-3) unions both rings.")

;;; Serialization helpers

(defun fzfa-replay--scrub-spec (spec snapshot)
  "Return a serialization-safe copy of SPEC.

Walks the plist and:
- Replaces function-shaped `:candidates' with SNAPSHOT (the
  exit-time output captured at session push).  Static-list and
  nil `:candidates' pass through.
- Drops slots whose value is a function — `:action', `:annotate',
  `:affix', `:group', any lambda the caller attached.  These can't
  round-trip through `prin1' / `read' as callables, and replay-
  from-file accepts the loss (the picker still works; the source's
  custom action just falls through to the default identity)."
  (cl-loop for (key value) on spec by #'cddr
           for safe =
           (cond
            ((and (eq key :candidates) (functionp value))
             snapshot)
            ((functionp value) :fzfa-replay--drop)
            (t value))
           unless (eq safe :fzfa-replay--drop)
           collect key and collect safe))

(defun fzfa-replay--scrub-session (session)
  "Return SESSION with each per-source spec scrubbed for disk."
  (let* ((sources (plist-get session :sources))
         (scrubbed
          (cl-map
           'vector
           (lambda (rec)
             (list :spec (fzfa-replay--scrub-spec
                          (plist-get rec :spec)
                          (plist-get rec :snapshot))
                   :command       (plist-get rec :command)
                   :display       (plist-get rec :display)
                   :initial-input (plist-get rec :initial-input)))
           sources)))
    (list :prompt     (plist-get session :prompt)
          :narrow-idx (plist-get session :narrow-idx)
          :timestamp  (plist-get session :timestamp)
          :directory  (plist-get session :directory)
          :sources    scrubbed)))

(defconst fzfa-replay--save-file-header
  ";;; -*- mode: emacs-lisp; coding: utf-8-emacs; -*-
;; fzfa-replay session log generated by `fzfa-replay-save-list'.
;; Auto-generated — do not hand-edit.
"
  "Header prepended to `fzfa-replay-file' on each save.")

;;; Save / load

(defun fzfa-replay-save-list ()
  "Save `fzfa--sessions' to `fzfa-replay-file'.

Truncates to `fzfa-replay-max-saved-items' before writing.  Each
session is passed through `fzfa-replay--scrub-session' to strip
non-readable function slots and substitute function-shaped
`:candidates' with their captured snapshot.  Writes via
`prin1' with `print-circle' on so propertized strings (e.g.
`fzfa-location' on swiper-class candidates) round-trip."
  (interactive)
  (condition-case err
      (let* ((trimmed (cl-subseq fzfa--sessions
                                 0 (min fzfa-replay-max-saved-items
                                        (length fzfa--sessions))))
             (scrubbed (mapcar #'fzfa-replay--scrub-session trimmed))
             (print-length nil)
             (print-level nil)
             (print-quoted t)
             (print-circle t))
        (with-temp-buffer
          (insert fzfa-replay--save-file-header)
          (insert "\n(setq fzfa-replay--persisted-sessions\n      '")
          (prin1 scrubbed (current-buffer))
          (insert ")\n")
          (write-region (point-min) (point-max)
                        (expand-file-name fzfa-replay-file))
          (when fzfa-replay-save-file-modes
            (set-file-modes (expand-file-name fzfa-replay-file)
                            fzfa-replay-save-file-modes))))
    (error
     (message "fzfa-replay-save-list: %s" (error-message-string err)))))

(defun fzfa-replay-load-list ()
  "Load saved sessions from `fzfa-replay-file' into
`fzfa-replay--persisted-sessions'.

No-op when the file does not exist (first run).  Errors during
load are logged via `message' — a corrupt or partial file should
not break the in-memory replay path."
  (interactive)
  (let ((file (expand-file-name fzfa-replay-file)))
    (when (file-readable-p file)
      (condition-case err
          (load-file file)
        (error
         (message "fzfa-replay-load-list: %s"
                  (error-message-string err)))))))

;;; Mode

(defun fzfa-replay--start-auto-save-timer ()
  "Install the idle auto-save timer if interval is positive."
  (when (and (numberp fzfa-replay-auto-save-interval)
             (> fzfa-replay-auto-save-interval 0))
    (setq fzfa-replay-auto-save-timer
          (run-with-idle-timer fzfa-replay-auto-save-interval
                               t
                               #'fzfa-replay-save-list))))

(defun fzfa-replay--cancel-auto-save-timer ()
  "Cancel the idle auto-save timer if installed."
  (when fzfa-replay-auto-save-timer
    (cancel-timer fzfa-replay-auto-save-timer)
    (setq fzfa-replay-auto-save-timer nil)))

;;;###autoload
(define-minor-mode fzfa-replay-mode
  "Persist `fzfa' session history across Emacs lifetimes.

When enabled:
- Loads the on-disk session list from `fzfa-replay-file' into
  `fzfa-replay--persisted-sessions'.
- Installs an idle timer (`fzfa-replay-auto-save-timer') that
  flushes `fzfa--sessions' every `fzfa-replay-auto-save-interval'
  seconds.
- Adds a final-save handler on `kill-emacs-hook'.

The in-memory replay path is unaffected — `fzfa-replay' works
whether or not this mode is on.  This mode only adds the disk
round-trip."
  :global t
  :group 'fzfa-replay
  (cond
   (fzfa-replay-mode
    (fzfa-replay-load-list)
    (fzfa-replay--start-auto-save-timer)
    (add-hook 'kill-emacs-hook #'fzfa-replay-save-list))
   (t
    (fzfa-replay--cancel-auto-save-timer)
    (remove-hook 'kill-emacs-hook #'fzfa-replay-save-list))))

(provide 'fzfa-replay)
;;; fzfa-replay.el ends here
