;;; fzfa-fuzz-producer.el --- Native producer boundary fuzzing  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 James Nguyen
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Sends generated byte streams through fzfa's command-source adapter and the
;; real fzf-native session API.  The harness checks that malformed producer
;; output becomes one visible failure, that valid prefix candidates survive,
;; and that neither NUL bytes nor partial malformed rows reach Emacs strings.
;; It also exercises the command assembled by the ugrep integration when
;; ugrep is installed.

;;; Code:

(require 'cl-lib)
(require 'fzfa-fuzz-core)

(declare-function fzf-native-async-generation "ext:fzf-native-module"
                  (handle))
(declare-function fzf-native-async-status "ext:fzf-native-module"
                  (handle &optional request-id))
(declare-function fzfa-ugrep "fzfa-ugrep" ())
(defvar fzf-native-async-highlight)

(defconst fzfa-fuzz-producer--words
  '("alpha" "beta" "same" "space here" "naive" "café" "你好" "x:y")
  "Candidate strings used at the native producer boundary.")

(defun fzfa-fuzz-producer--utf8 (string)
  "Return STRING encoded as an exact unibyte UTF-8 string."
  (encode-coding-string string 'utf-8 t))

(defun fzfa-fuzz-producer--lines (strings &optional ending)
  "Encode STRINGS as producer records terminated by ENDING.

ENDING defaults to a line feed."
  (apply #'concat
         (mapcar (lambda (string)
                   (concat (fzfa-fuzz-producer--utf8 string)
                           (or ending (unibyte-string ?\n))))
                 strings)))

(defun fzfa-fuzz-producer--python-command (bytes exit-status)
  "Return a trusted Python command that writes BYTES and exits EXIT-STATUS."
  (let ((python (or (executable-find "python3")
                    (error "Producer fuzz requires python3"))))
    (format
     "%s -u -c %s %s %d"
     (shell-quote-argument python)
     (shell-quote-argument
      (concat
       "import sys; "
       "sys.stdout.buffer.write(bytes.fromhex(sys.argv[1])); "
       "sys.stdout.buffer.flush(); "
       "raise SystemExit(int(sys.argv[2]))"))
     (shell-quote-argument
      (mapconcat (lambda (byte) (format "%02x" byte)) bytes ""))
     exit-status)))

(defun fzfa-fuzz-producer--contains-nul-p (string)
  "Return non-nil when STRING contains a zero byte."
  (cl-position 0 (string-to-list string)))

(defun fzfa-fuzz-producer--wait (source handle seed trace)
  "Wait for SOURCE on HANDLE to return its final output.

SEED and TRACE identify a timeout in the reproducer message."
  (let ((deadline (+ (float-time) 8.0))
        output status)
    (while (and (< (float-time) deadline)
                (not (and (eq (car-safe output) 'final)
                          (plist-get status :reader-done))))
      (setq output (fzfa--source-async-out source "" 1000)
            status (fzf-native-async-status handle))
      (unless (and (eq (car-safe output) 'final)
                   (plist-get status :reader-done))
        (sleep-for 0.005)))
    (unless (and (eq (car-safe output) 'final)
                 (plist-get status :reader-done))
      (fzfa-fuzz--fail seed trace
                       "producer did not reach a final result: %S / %S"
                       output status))
    (list output status)))

(defun fzfa-fuzz-producer--failure-required-p (policy status)
  "Return whether POLICY requires a failure for STATUS.

POLICY is nil, non-nil, or `either'."
  (if (eq policy 'either)
      (eq (plist-get status :producer-state) 'failed)
    policy))

(defun fzfa-fuzz-producer--run-command (seed spec command &optional directory)
  "Run COMMAND as the native producer described by SPEC for SEED.

Return a plist containing the final candidates, native status, and printed
messages.  DIRECTORY defaults to `default-directory'."
  (let* ((trace (list :target 'native-producer
                      :kind (plist-get spec :kind)
                      :bytes (length (or (plist-get spec :bytes) ""))
                      :exit (plist-get spec :exit)))
         ;; fzf-native reads these values when the handle starts.
         (fzfa-max-line-length
          (and (plist-member spec :max-line-length)
               (plist-get spec :max-line-length)))
         (fzfa-highlight nil)
         (fzf-native-async-highlight nil)
         (source (fzfa-make-source
                  :spec (list :name "native-fuzz" :command command
                              :directory directory)
                  :command command :directory directory))
         (handle (fzfa--spawn command (fzfa-source-directory source)))
         (fzfa--async-failed-producers nil)
         messages result)
    (setf (fzfa-source-current-cmd source) command
          (fzfa-source-handle source) handle)
    (unwind-protect
        (cl-letf (((symbol-function 'fzfa--print)
                   (lambda (format-string &rest args)
                     (push (apply #'format format-string args) messages))))
          (pcase-let* ((`(,output ,status)
                        (fzfa-fuzz-producer--wait
                         source handle seed trace))
                       (candidates
                        (mapcar #'substring-no-properties (nth 1 output)))
                       (policy (plist-get spec :failure))
                       (failure-required
                        (fzfa-fuzz-producer--failure-required-p policy status)))
            ;; Stable redraws must reuse the result and must not report a dead
            ;; producer again.
            (dotimes (_ 3)
              (unless (eq (car-safe (fzfa--source-async-out
                                     source "" 1000))
                          'final)
                (fzfa-fuzz--fail seed trace
                                 "stable redraw lost the final result")))
            (unless (fzfa-fuzz--proper-list-p candidates)
              (fzfa-fuzz--fail seed trace
                               "candidate output is not a proper list: %S"
                               candidates))
            (when-let* ((bad (cl-find-if
                              #'fzfa-fuzz-producer--contains-nul-p
                              candidates)))
              (fzfa-fuzz--fail seed trace
                               "a NUL-bearing candidate escaped: %S" bad))
            (when (plist-member spec :expected)
              (unless (equal candidates (plist-get spec :expected))
                (fzfa-fuzz--fail
                 seed trace "candidates are %S, expected %S"
                 candidates (plist-get spec :expected))))
            (if failure-required
                (unless (and (eq (plist-get status :producer-state) 'failed)
                             (plist-get status :producer-error)
                             (= (length messages) 1))
                  (fzfa-fuzz--fail
                   seed trace
                   "producer failure was not reported once: %S / %S"
                   status (nreverse messages)))
              (unless (and (eq (plist-get status :producer-state) 'complete)
                           (null (plist-get status :producer-error))
                           (null messages))
                (fzfa-fuzz--fail
                 seed trace "clean producer ended unexpectedly: %S / %S"
                 status (nreverse messages))))
            (setq result
                  (list :candidates candidates :status status
                        :messages (nreverse messages)))))
      (fzfa-source--stop source))
    (when (fzf-native-async-generation handle)
      (fzfa-fuzz--fail seed trace "source teardown left its handle alive"))
    result))

(defun fzfa-fuzz-producer--case (_seed rng)
  "Generate one native producer case using RNG."
  (let* ((kind (fzfa-fuzz--pick
                rng '(plain crlf ansi unterminated invalid long nul nonzero
                            empty duplicate)))
         (count (1+ (fzfa-fuzz--integer rng 6)))
         (words (cl-loop repeat count
                         collect (fzfa-fuzz--pick
                                  rng fzfa-fuzz-producer--words))))
    (pcase kind
      ('plain
       (list :kind kind :bytes (fzfa-fuzz-producer--lines words)
             :exit 0 :failure nil :expected words))
      ('crlf
       (list :kind kind
             :bytes (fzfa-fuzz-producer--lines words (unibyte-string ?\r ?\n))
             :exit 0 :failure nil :expected words))
      ('ansi
       (let* ((word (car words))
              (bytes (concat (unibyte-string 27) "[31m"
                             (fzfa-fuzz-producer--utf8 word)
                             (unibyte-string 27) "[0m\n")))
         (list :kind kind :bytes bytes :exit 0 :failure nil
               :expected (list word))))
      ('unterminated
       (let ((word (car words)))
         (list :kind kind
               :bytes (concat (fzfa-fuzz-producer--utf8 word)
                              (unibyte-string 27) "[31")
               :exit 0 :failure nil :expected (list word))))
      ('invalid
       (let* ((prefix (fzfa-fuzz-producer--utf8 (car words)))
              (row (concat prefix
                           (unibyte-string (+ #x80
                                             (fzfa-fuzz--integer rng #x80)))
                           "tail")))
         (list :kind kind :bytes (concat row "\n")
               :exit 0 :failure nil :expected (list row))))
      ('long
       (let ((row (make-string (+ 300 (fzfa-fuzz--integer rng 1700)) ?x)))
         (list :kind kind :bytes (concat row "\n")
               :exit 0 :failure nil :expected (list row))))
      ('nul
       (let* ((prefix (butlast words 1))
              (bad (fzfa-fuzz-producer--utf8 (or (car (last words)) "bad")))
              (bytes (concat (fzfa-fuzz-producer--lines prefix)
                             bad (unibyte-string 0) "hidden\nlate\n")))
         (list :kind kind :bytes bytes :exit 0 :failure t
               :expected prefix)))
      ('nonzero
       (list :kind kind :bytes (fzfa-fuzz-producer--lines words)
             :exit (1+ (fzfa-fuzz--integer rng 20))
             :failure t :expected words))
      ('empty
       (list :kind kind :bytes "" :exit 0 :failure nil :expected nil))
      ('duplicate
       (let ((word (car words)))
         (list :kind kind
               :bytes (fzfa-fuzz-producer--lines (list word word word))
               :exit 0 :failure nil :expected (list word word word)))))))

(defun fzfa-fuzz-producer--run-spec (seed spec)
  "Run generated producer SPEC for SEED."
  (fzfa-fuzz-producer--run-command
   seed spec
   (fzfa-fuzz-producer--python-command
    (plist-get spec :bytes) (plist-get spec :exit))))

(defun fzfa-fuzz-producer--write-bytes (file bytes)
  "Write exact BYTES to FILE."
  (let ((coding-system-for-write 'no-conversion))
    (write-region bytes nil file nil 'silent)))

(defun fzfa-fuzz-producer--run-shell (command directory)
  "Run COMMAND in DIRECTORY and return (EXIT . STDOUT-BYTES)."
  (let ((default-directory (file-name-as-directory directory))
        (coding-system-for-read 'no-conversion))
    (with-temp-buffer
      (set-buffer-multibyte nil)
      (let ((exit (call-process shell-file-name nil t nil
                                shell-command-switch command)))
        (cons exit (buffer-string))))))

(defun fzfa-fuzz-tools-batch ()
  "Exercise external-tool defaults at the native producer boundary."
  (if (not (executable-find "ugrep"))
      (princ "SKIP fzfa tool fuzz: ugrep is not installed\n")
    (require 'fzfa-ugrep)
    (let (args command)
      (cl-letf (((symbol-function 'fzfa-completing-read)
                 (lambda (&rest captured)
                   (setq args captured)
                   nil)))
        (fzfa-ugrep))
      (setq command (plist-get args :command))
      (unless (and (stringp command) (string-match-p "\\bugrep\\b" command))
        (error "Tool fuzz could not capture the ugrep command: %S" args))
      (let* ((directory (make-temp-file "fzfa-ugrep-fuzz-" t))
             (emms-directory (expand-file-name "emms" directory))
             (header (fzfa-fuzz-producer--lines
                      (make-list 800 "plain ASCII header")))
             (late-bytes (concat header "late-binary\0tail\n"))
             raw)
        (unwind-protect
            (progn
              (make-directory emms-directory)
              (fzfa-fuzz-producer--write-bytes
               (expand-file-name "normal.txt" directory)
               "visible-alpha\n")
              (dolist (file (list (expand-file-name "manual.info" directory)
                                  (expand-file-name "manual.info-1" directory)
                                  (expand-file-name "cache" emms-directory)))
                (fzfa-fuzz-producer--write-bytes file late-bytes))
              ;; A path not covered by the integration's explicit exclusions
              ;; checks the containment boundary: ugrep may omit it as binary,
              ;; or fzf-native must reject its NUL if it reaches the pipe.
              (fzfa-fuzz-producer--write-bytes
               (expand-file-name "late.bin" directory) late-bytes)
              (setq raw (fzfa-fuzz-producer--run-shell command directory))
              (unless (memq (car raw) '(0 1))
                (error "Ugrep exited %S" (car raw)))
              (dolist (excluded '("manual.info" "manual.info-1" "emms/cache"))
                (when (string-match-p (regexp-quote excluded) (cdr raw))
                  (error "Excluded path reached ugrep stdout: %s"
                         excluded)))
              (let* ((nul-reached
                      (fzfa-fuzz-producer--contains-nul-p (cdr raw)))
                     (spec (list :kind 'ugrep-default :bytes (cdr raw)
                                 :exit (car raw)
                                 :failure (if nul-reached t nil)))
                     (result (fzfa-fuzz-producer--run-command
                              (fzfa-fuzz--seed) spec command directory)))
                (when-let* ((bad (cl-find-if
                                  (lambda (candidate)
                                    (or (string-match-p "manual\\.info"
                                                        candidate)
                                        (string-match-p "emms/cache"
                                                        candidate)))
                                  (plist-get result :candidates))))
                  (error "Excluded ugrep candidate escaped: %S" bad))
                (princ
                 (format
                  (concat "fzfa ugrep fuzz passed (%s; native boundary %s "
                          "late binary output)\n")
                  (car (process-lines "ugrep" "--version"))
                  (if nul-reached "rejected" "did not receive")))))
          (delete-directory directory t))))))

(defun fzfa-fuzz-producer-batch ()
  "Run deterministic native producer boundary cases."
  (unless (fzfa--command-api-p)
    (error "Producer fuzz requires the fzf-native 2.7 session API"))
  (let* ((root-seed (fzfa-fuzz--seed))
         (cases (fzfa-fuzz--env-natural "FZFA_FUZZ_CASES" 100))
         (fixed (list :kind 'fixed-nul
                      :bytes (concat "valid\nab" (unibyte-string 0)
                                     "cd\nlate\n")
                      :exit 0 :failure t :expected '("valid"))))
    (fzfa-fuzz-producer--run-spec root-seed fixed)
    (dotimes (index cases)
      (let* ((seed (+ root-seed index))
             (rng (fzfa-fuzz-rng-create :state seed)))
        (fzfa-fuzz-producer--run-spec
         seed (fzfa-fuzz-producer--case seed rng))))
    (princ (format "fzfa producer fuzz passed (%d cases, root seed %d)\n"
                   cases root-seed))))

(provide 'fzfa-fuzz-producer)
;;; fzfa-fuzz-producer.el ends here
