;;; fzfa-fuzz-schedule.el --- Real timer and process fuzzing  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 James Nguyen
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Runs a small replayable schedule matrix on Emacs's real event loop.  This
;; complements the fast fake scheduler in fzfa-fuzz-state.el.  It exercises
;; reversed producer callbacks, teardown before a callback, shell restart and
;; stop after partial output, and debounced command edits.

;;; Code:

(require 'cl-lib)
(require 'fzfa-fuzz-producer)

(declare-function fzf-native-async-generation "ext:fzf-native-module"
                  (handle))
(declare-function fzf-native-async-status "ext:fzf-native-module"
                  (handle &optional request-id))

(defvar fzfa-fuzz-schedule--timers nil
  "Real timers owned by the current schedule trace.")

(defvar fzfa-fuzz-schedule--result-mutator nil
  "Test-only function for corrupting a schedule result.")

(defconst fzfa-fuzz-schedule--scenarios
  '(callback-order callback-stop command-restart command-stop debounce)
  "Real scheduler scenarios generated by this lane.")

(defun fzfa-fuzz-schedule--delay-p (value)
  "Return non-nil when VALUE is a bounded real delay."
  (and (numberp value) (<= 0 value) (<= value 1.0)))

(defun fzfa-fuzz-schedule--schedule (delay function)
  "Run FUNCTION after DELAY and track its timer."
  (let ((timer (run-at-time delay nil function)))
    (push timer fzfa-fuzz-schedule--timers)
    timer))

(defun fzfa-fuzz-schedule--timer-active-p (timer)
  "Return non-nil when TIMER remains in a real Emacs timer queue."
  (or (memq timer timer-list) (memq timer timer-idle-list)))

(defun fzfa-fuzz-schedule--active-timer-count ()
  "Return the number of tracked timers which have not fired or been canceled."
  (cl-count-if #'fzfa-fuzz-schedule--timer-active-p
               fzfa-fuzz-schedule--timers))

(defun fzfa-fuzz-schedule--cancel-timers ()
  "Cancel all tracked timers and clear the tracking list."
  (dolist (timer fzfa-fuzz-schedule--timers)
    (when (timerp timer) (cancel-timer timer)))
  (setq fzfa-fuzz-schedule--timers nil))

(defun fzfa-fuzz-schedule--new-idle-timers (before)
  "Return idle timers present now but absent from BEFORE."
  (cl-remove-if (lambda (timer) (memq timer before)) timer-idle-list))

(defun fzfa-fuzz-schedule--cancel-idle-timers (timers)
  "Cancel each timer in TIMERS."
  (dolist (timer timers)
    (when (timerp timer) (cancel-timer timer))))

(defun fzfa-fuzz-schedule--wait (trace label predicate observed)
  "Drive the real event loop until PREDICATE or fail TRACE at LABEL.

OBSERVED is a function returning timeout evidence."
  (let ((deadline (+ (float-time) 2.0)))
    (while (and (< (float-time) deadline) (not (funcall predicate)))
      (accept-process-output nil 0.005))
    (unless (funcall predicate)
      (fzfa-fuzz--fail-observation
       (plist-get trace :case-seed) trace label (funcall observed)
       "real scheduler timed out waiting for %S" label))))

(defun fzfa-fuzz-schedule--check (trace expected observed)
  "Require OBSERVED to equal EXPECTED for TRACE."
  (let* ((scenario (plist-get (plist-get trace :initial-state) :scenario))
         (observed
          (if fzfa-fuzz-schedule--result-mutator
              (funcall fzfa-fuzz-schedule--result-mutator
                       scenario (copy-tree observed))
            observed)))
    (unless (equal expected observed)
      (fzfa-fuzz--fail-observation
       (plist-get trace :case-seed) trace expected observed
       "real scheduler result differs for %S" scenario))
    observed))

(defun fzfa-fuzz-schedule--trace
    (root-seed case-seed scenario actions)
  "Return a replayable real scheduler trace."
  (fzfa-fuzz-trace-create
   'real-schedule root-seed case-seed
   (list :scenario scenario) actions))

(defun fzfa-fuzz-schedule--generated-trace (root-seed case-seed)
  "Generate one real scheduler trace for CASE-SEED."
  (let* ((rng (fzfa-fuzz-rng-create :state case-seed))
         (scenario (nth (% case-seed (length fzfa-fuzz-schedule--scenarios))
                        fzfa-fuzz-schedule--scenarios))
         (jitter (/ (fzfa-fuzz--integer rng 5) 1000.0))
         (slow (+ 0.050 jitter))
         (fast (+ 0.002 (/ (fzfa-fuzz--integer rng 3) 1000.0)))
         (edit 0.002)
         (old (format "old-%d" case-seed))
         (new (format "new-%d" case-seed)))
    (fzfa-fuzz-schedule--trace
     root-seed case-seed scenario
     (pcase scenario
       ('callback-order
        (list (list 'fetch old slow)
              (list 'after edit 'fetch new fast)
              '(await)))
       ('callback-stop
        (list (list 'fetch old slow)
              (list 'after fast 'kill-buffer-and-stop)
              '(await)))
       ('command-restart
        (list
         (list 'start
               (mapcar #'fzfa-fuzz-trace-bytes-to-hex
                       (list (fzfa-fuzz-producer--lines (list old))
                             (fzfa-fuzz-producer--lines
                              (list (concat old "-tail")))))
               slow)
         (list 'after-partial 'restart fast
               (list (fzfa-fuzz-trace-bytes-to-hex
                      (fzfa-fuzz-producer--lines (list new))))
               0.0 (list new))
         '(await)))
       ('command-stop
        (list
         (list 'start
               (mapcar #'fzfa-fuzz-trace-bytes-to-hex
                       (list (fzfa-fuzz-producer--lines (list old))
                             (fzfa-fuzz-producer--lines
                              (list (concat old "-tail")))))
               slow)
         (list 'after-partial 'kill-buffer-and-stop fast)
         '(await)))
       ('debounce
        (list
         (list 'debounce
               (fzfa-fuzz-trace-bytes-to-hex
                (fzfa-fuzz-producer--lines (list old))))
         (list 'after edit 'debounce
               (fzfa-fuzz-trace-bytes-to-hex
                (fzfa-fuzz-producer--lines (list (concat old "-edit")))))
         (list 'after (* 2 edit) 'debounce
               (fzfa-fuzz-trace-bytes-to-hex
                (fzfa-fuzz-producer--lines (list new))))
         (list 'await (list new))))))))

(defun fzfa-fuzz-schedule--decode-chunks (hexes)
  "Decode non-empty HEXES into exact byte chunks."
  (unless (and (consp hexes) (cl-every #'stringp hexes))
    (error "Malformed real scheduler chunks: %S" hexes))
  (mapcar #'fzfa-fuzz-trace-hex-to-bytes hexes))

(defun fzfa-fuzz-schedule--decode-trace (trace)
  "Validate TRACE and return its scenario and actions."
  (let* ((initial (plist-get trace :initial-state))
         (keys (fzfa-fuzz-trace--plist-keys
                initial "real-schedule initial state" '(:scenario)))
         (scenario (plist-get initial :scenario))
         (actions (plist-get trace :actions)))
    (fzfa-fuzz-trace--require-keys
     keys '(:scenario) "real-schedule initial state")
    (unless (memq scenario fzfa-fuzz-schedule--scenarios)
      (error "Unknown real scheduler scenario: %S" scenario))
    (pcase (cons scenario actions)
      (`(callback-order
         (fetch ,old ,slow) (after ,edit fetch ,new ,fast) (await))
       (unless (and (stringp old) (stringp new)
                    (fzfa-fuzz-schedule--delay-p slow)
                    (fzfa-fuzz-schedule--delay-p edit)
                    (fzfa-fuzz-schedule--delay-p fast)
                    (> slow (+ edit fast)))
         (error "Malformed callback-order schedule: %S" actions)))
      (`(callback-stop
         (fetch ,query ,delivery)
         (after ,stop-delay kill-buffer-and-stop) (await))
       (unless (and (stringp query)
                    (fzfa-fuzz-schedule--delay-p delivery)
                    (fzfa-fuzz-schedule--delay-p stop-delay)
                    (> delivery stop-delay))
         (error "Malformed callback-stop schedule: %S" actions)))
      (`(command-restart
         (start ,old-hexes ,old-pause)
         (after-partial restart ,delay ,new-hexes ,new-pause ,expected)
         (await))
       (fzfa-fuzz-schedule--decode-chunks old-hexes)
       (fzfa-fuzz-schedule--decode-chunks new-hexes)
       (unless (and (fzfa-fuzz-schedule--delay-p old-pause)
                    (fzfa-fuzz-schedule--delay-p delay)
                    (fzfa-fuzz-schedule--delay-p new-pause)
                    (consp expected) (cl-every #'stringp expected))
         (error "Malformed command-restart schedule: %S" actions)))
      (`(command-stop
         (start ,hexes ,pause)
         (after-partial kill-buffer-and-stop ,delay) (await))
       (fzfa-fuzz-schedule--decode-chunks hexes)
       (unless (and (fzfa-fuzz-schedule--delay-p pause)
                    (fzfa-fuzz-schedule--delay-p delay))
         (error "Malformed command-stop schedule: %S" actions)))
      (`(debounce
         (debounce ,first) (after ,delay-a debounce ,second)
         (after ,delay-b debounce ,final) (await ,expected))
       (mapc #'fzfa-fuzz-trace-hex-to-bytes (list first second final))
       (unless (and (fzfa-fuzz-schedule--delay-p delay-a)
                    (fzfa-fuzz-schedule--delay-p delay-b)
                    (< delay-a delay-b 0.02)
                    (consp expected) (cl-every #'stringp expected))
         (error "Malformed debounce schedule: %S" actions)))
      (_ (error "Actions do not match real scheduler scenario %S: %S"
                scenario actions)))
    (list :scenario scenario :actions actions)))

(defun fzfa-fuzz-schedule--callback-order (trace actions)
  "Run callback-order TRACE described by ACTIONS."
  (pcase-let* ((`((fetch ,old ,slow)
                  (after ,edit fetch ,new ,fast) (await)) actions)
               (callbacks 0)
               (refreshes 0)
               (before-idle (copy-sequence timer-idle-list))
               (queued-idle nil)
               (source nil))
    (unwind-protect
        (progn
          (setq source
                (fzfa-make-source
                 :spec
                 (list
                  :candidates
                  (lambda (input callback)
                    (let ((delay (if (equal input old) slow fast))
                          (value (list (concat "result:" input))))
                      (fzfa-fuzz-schedule--schedule
                       delay
                       (lambda ()
                         (cl-incf callbacks)
                         (funcall callback value))))))))
          (fzfa--source-fetch source old (lambda () (cl-incf refreshes)))
          (fzfa-fuzz-schedule--schedule
           edit
           (lambda ()
             (fzfa--source-fetch
              source new (lambda () (cl-incf refreshes)))))
          (fzfa-fuzz-schedule--wait
           trace '(:callbacks 2)
           (lambda () (= callbacks 2))
           (lambda () (list :callbacks callbacks :refreshes refreshes
                            :snapshot (fzfa-source-snapshot source))))
          ;; Batch Emacs does not service idle timers.  The live lane exercises
          ;; their execution; this lane checks that exactly the current
          ;; callback queued one and that the stale callback queued none.
          (setq queued-idle
                (fzfa-fuzz-schedule--new-idle-timers before-idle))
          (fzfa-fuzz-schedule--check
           trace
           (list :snapshot (list (concat "result:" new))
                 :callbacks 2 :refreshes 0 :queued-idle-refreshes 1
                 :active-timers 0)
           (list :snapshot (fzfa-source-snapshot source)
                 :callbacks callbacks :refreshes refreshes
                 :queued-idle-refreshes (length queued-idle)
                 :active-timers
                 (fzfa-fuzz-schedule--active-timer-count))))
      (when source (fzfa-source--stop source))
      (fzfa-fuzz-schedule--cancel-idle-timers queued-idle)
      (fzfa-fuzz-schedule--cancel-timers))))

(defun fzfa-fuzz-schedule--callback-stop (trace actions)
  "Run callback-stop TRACE described by ACTIONS."
  (pcase-let* ((`((fetch ,query ,delivery)
                  (after ,stop-delay kill-buffer-and-stop) (await)) actions)
               (owner (generate-new-buffer " *fzfa-fuzz-owner*"))
               (callbacks 0)
               (refreshes 0)
               (before-idle (copy-sequence timer-idle-list))
               (queued-idle nil)
               (stopped nil)
               (source nil))
    (unwind-protect
        (progn
          (setq source
                (fzfa-make-source
                 :spec
                 (list
                  :candidates
                  (lambda (_input callback)
                    (fzfa-fuzz-schedule--schedule
                     delivery
                     (lambda ()
                       (cl-incf callbacks)
                       (funcall callback '("late"))))))))
          (fzfa--source-fetch
           source query
           (lambda ()
             (when (buffer-live-p owner) (cl-incf refreshes))))
          (fzfa-fuzz-schedule--schedule
           stop-delay
           (lambda ()
             (kill-buffer owner)
             (fzfa-source--stop source)
             (setq stopped t)))
          (fzfa-fuzz-schedule--wait
           trace '(:stopped t :callbacks 1)
           (lambda () (and stopped (= callbacks 1)))
           (lambda () (list :stopped stopped :callbacks callbacks)))
          (setq queued-idle
                (fzfa-fuzz-schedule--new-idle-timers before-idle))
          (fzfa-fuzz-schedule--check
           trace
           '(:snapshot nil :callbacks 1 :refreshes 0
             :owner-live nil :queued-idle-refreshes 0 :active-timers 0)
           (list :snapshot (fzfa-source-snapshot source)
                 :callbacks callbacks :refreshes refreshes
                 :owner-live (buffer-live-p owner)
                 :queued-idle-refreshes (length queued-idle)
                 :active-timers
                 (fzfa-fuzz-schedule--active-timer-count))))
      (when (buffer-live-p owner) (kill-buffer owner))
      (when source (fzfa-source--stop source))
      (fzfa-fuzz-schedule--cancel-idle-timers queued-idle)
      (fzfa-fuzz-schedule--cancel-timers))))

(defun fzfa-fuzz-schedule--wait-for-partial (trace handle)
  "Wait until live HANDLE has collected at least one row for TRACE."
  (fzfa-fuzz-schedule--wait
   trace 'partial-command-output
   (lambda ()
     (when-let* ((status (fzf-native-async-status handle)))
       (and (not (plist-get status :reader-done))
            (> (or (fzfa--async-collected-total status) 0) 0))))
   (lambda () (fzf-native-async-status handle))))

(defun fzfa-fuzz-schedule--command-result (trace source handle expected)
  "Wait for SOURCE on HANDLE and return its stable result evidence."
  (pcase-let* ((`(,output ,status ,_observations)
                (fzfa-fuzz-producer--wait source handle
                                          (plist-get trace :case-seed) trace)))
    (list :candidates
          (mapcar #'substring-no-properties (nth 1 output))
          :producer-state (plist-get status :producer-state)
          :reader-done (and (plist-get status :reader-done) t)
          :expected expected)))

(defun fzfa-fuzz-schedule--command-restart (trace actions)
  "Run command-restart TRACE described by ACTIONS."
  (pcase-let* ((`((start ,old-hexes ,old-pause)
                  (after-partial restart ,delay
                   ,new-hexes ,new-pause ,expected)
                  (await)) actions)
               (old-chunks (fzfa-fuzz-schedule--decode-chunks old-hexes))
               (new-chunks (fzfa-fuzz-schedule--decode-chunks new-hexes))
               (old-command (fzfa-fuzz-producer--python-chunk-command
                             old-chunks old-pause 0))
               (new-command (fzfa-fuzz-producer--python-chunk-command
                             new-chunks new-pause 0))
               (source (fzfa-make-source :command old-command))
               (old-handle (fzfa--spawn old-command default-directory))
               (refreshes 0)
               (current-handle nil))
    (setf (fzfa-source-handle source) old-handle
          (fzfa-source-current-cmd source) old-command)
    (unwind-protect
        (progn
          (fzfa-fuzz-schedule--wait-for-partial trace old-handle)
          (fzfa-fuzz-schedule--schedule
           delay
           (lambda ()
             (fzfa-source--restart
              source new-command (lambda () (cl-incf refreshes)))))
          (fzfa-fuzz-schedule--wait
           trace 'command-restarted
           (lambda () (and (= refreshes 1)
                           (fzfa-source-handle source)
                           (not (eq old-handle
                                    (fzfa-source-handle source)))))
           (lambda () (list :refreshes refreshes
                            :handle (fzfa-source-handle source))))
          (setq current-handle (fzfa-source-handle source))
          (let ((result
                 (fzfa-fuzz-schedule--command-result
                  trace source current-handle expected)))
            (fzfa-source--stop source)
            (fzfa-fuzz-schedule--check
             trace
             (list :candidates expected :producer-state 'complete
                   :reader-done t :expected expected
                   :refreshes 1 :old-generation nil
                   :current-generation nil :active-timers 0)
             (append result
                     (list :refreshes refreshes
                           :old-generation
                           (fzf-native-async-generation old-handle)
                           :current-generation
                           (fzf-native-async-generation current-handle)
                           :active-timers
                           (fzfa-fuzz-schedule--active-timer-count))))))
      (fzfa-source--stop source)
      (fzfa-fuzz-schedule--cancel-timers))))

(defun fzfa-fuzz-schedule--command-stop (trace actions)
  "Run command-stop TRACE described by ACTIONS."
  (pcase-let* ((`((start ,hexes ,pause)
                  (after-partial kill-buffer-and-stop ,delay) (await)) actions)
               (chunks (fzfa-fuzz-schedule--decode-chunks hexes))
               (command (fzfa-fuzz-producer--python-chunk-command
                         chunks pause 0))
               (source (fzfa-make-source :command command))
               (handle (fzfa--spawn command default-directory))
               (owner (generate-new-buffer " *fzfa-fuzz-command-owner*"))
               (stopped nil))
    (setf (fzfa-source-handle source) handle
          (fzfa-source-current-cmd source) command)
    (unwind-protect
        (progn
          (fzfa-fuzz-schedule--wait-for-partial trace handle)
          (fzfa-fuzz-schedule--schedule
           delay
           (lambda ()
             (kill-buffer owner)
             (fzfa-source--stop source)
             (setq stopped t)))
          (fzfa-fuzz-schedule--wait
           trace 'command-stopped
           (lambda () (and stopped
                           (null (fzf-native-async-generation handle))))
           (lambda () (list :stopped stopped
                            :generation
                            (fzf-native-async-generation handle))))
          (fzfa-fuzz-schedule--check
           trace
           '(:partial-seen t :source-handle nil :generation nil
             :owner-live nil :active-timers 0)
           (list :partial-seen t
                 :source-handle (fzfa-source-handle source)
                 :generation (fzf-native-async-generation handle)
                 :owner-live (buffer-live-p owner)
                 :active-timers
                 (fzfa-fuzz-schedule--active-timer-count))))
      (when (buffer-live-p owner) (kill-buffer owner))
      (fzfa-source--stop source)
      (fzfa-fuzz-schedule--cancel-timers))))

(defun fzfa-fuzz-schedule--debounce (trace actions)
  "Run debounced command edits in TRACE described by ACTIONS."
  (pcase-let* ((`((debounce ,first-hex)
                  (after ,delay-a debounce ,second-hex)
                  (after ,delay-b debounce ,final-hex)
                  (await ,expected)) actions)
               (commands
                (mapcar
                 (lambda (hex)
                   (fzfa-fuzz-producer--python-chunk-command
                    (list (fzfa-fuzz-trace-hex-to-bytes hex)) 0 0))
                 (list first-hex second-hex final-hex)))
               (source (fzfa-make-source :command ""))
               (refreshes 0)
               (fzfa-shell-command-debounce 0.02)
               (fzfa-shell-command-throttle 0.0)
               (current-handle nil))
    (unwind-protect
        (progn
          (fzfa-source--debounce-restart
           source (nth 0 commands) (lambda () (cl-incf refreshes)))
          (fzfa-fuzz-schedule--schedule
           delay-a
           (lambda ()
             (fzfa-source--debounce-restart
              source (nth 1 commands) (lambda () (cl-incf refreshes)))))
          (fzfa-fuzz-schedule--schedule
           delay-b
           (lambda ()
             (fzfa-source--debounce-restart
              source (nth 2 commands) (lambda () (cl-incf refreshes)))))
          (fzfa-fuzz-schedule--wait
           trace 'final-debounced-command
           (lambda () (and (= refreshes 1)
                           (fzfa-source-handle source)
                           (equal (fzfa-source-current-cmd source)
                                  (nth 2 commands))))
           (lambda () (list :refreshes refreshes
                            :command (fzfa-source-current-cmd source))))
          (setq current-handle (fzfa-source-handle source))
          (let ((result
                 (fzfa-fuzz-schedule--command-result
                  trace source current-handle expected)))
            (fzfa-source--stop source)
            (fzfa-fuzz-schedule--check
             trace
             (list :candidates expected :producer-state 'complete
                   :reader-done t :expected expected :refreshes 1
                   :restart-timer nil :generation nil :active-timers 0)
             (append
              result
              (list :refreshes refreshes
                    :restart-timer (fzfa-source-restart-timer source)
                    :generation
                    (fzf-native-async-generation current-handle)
                    :active-timers
                    (fzfa-fuzz-schedule--active-timer-count))))))
      (fzfa-source--stop source)
      (fzfa-fuzz-schedule--cancel-timers))))

(defun fzfa-fuzz-schedule-run-trace (trace)
  "Run one validated real scheduler TRACE without random generation."
  (fzfa-fuzz-trace-validate trace)
  (unless (eq (plist-get trace :target) 'real-schedule)
    (error "Unsupported scheduler trace target: %S"
           (plist-get trace :target)))
  (fzfa-fuzz--run-trace
   trace
   (lambda ()
     (let* ((description (fzfa-fuzz-schedule--decode-trace trace))
            (scenario (plist-get description :scenario))
            (actions (plist-get description :actions))
            (fzfa-fuzz-schedule--timers nil)
            (fzfa--async-failed-producers nil))
       (pcase scenario
         ('callback-order
          (fzfa-fuzz-schedule--callback-order trace actions))
         ('callback-stop
          (fzfa-fuzz-schedule--callback-stop trace actions))
         ('command-restart
          (fzfa-fuzz-schedule--command-restart trace actions))
         ('command-stop
          (fzfa-fuzz-schedule--command-stop trace actions))
         ('debounce (fzfa-fuzz-schedule--debounce trace actions)))))))

(defun fzfa-fuzz-schedule-selftest-batch ()
  "Require real scheduler oracles to kill controlled canaries."
  (fzfa-fuzz--expect-detection
   "stale-callback-published" "real scheduler result differs"
   (lambda ()
     (let ((fzfa-fuzz-schedule--result-mutator
            (lambda (scenario result)
              (if (eq scenario 'callback-order)
                  (plist-put result :snapshot '("result:old"))
                result))))
       (fzfa-fuzz-schedule-run-trace
        (fzfa-fuzz-schedule--generated-trace 9601 9605)))))
  (fzfa-fuzz--expect-detection
   "teardown-left-timer" "real scheduler result differs"
   (lambda ()
     (let ((fzfa-fuzz-schedule--result-mutator
            (lambda (scenario result)
              (if (eq scenario 'callback-stop)
                  (plist-put result :active-timers 1)
                result))))
       (fzfa-fuzz-schedule-run-trace
        (fzfa-fuzz-schedule--generated-trace 9602 9606)))))
  (princ "fzfa real scheduler self-test passed (2 canaries killed)\n"))

(defun fzfa-fuzz-schedule-batch ()
  "Run generated cases on Emacs's real timer and process scheduler."
  (unless (fzfa--command-api-p)
    (error "Real scheduler fuzz requires the fzf-native 2.7 session API"))
  (let* ((root-seed (fzfa-fuzz--seed))
         (cases (fzfa-fuzz--env-natural "FZFA_FUZZ_CASES" 20))
         reached)
    (dotimes (index cases)
      (let* ((seed (+ root-seed index))
             (trace (fzfa-fuzz-schedule--generated-trace root-seed seed))
             (scenario (plist-get (plist-get trace :initial-state)
                                  :scenario)))
        (cl-pushnew scenario reached)
        (fzfa-fuzz-schedule-run-trace trace)))
    (dolist (scenario fzfa-fuzz-schedule--scenarios)
      (unless (memq scenario reached)
        (error "Real scheduler campaign did not reach %S" scenario)))
    (princ
     (format "fzfa real scheduler fuzz passed (%d cases across %S, root seed %d)\n"
             cases fzfa-fuzz-schedule--scenarios root-seed))))

(provide 'fzfa-fuzz-schedule)
;;; fzfa-fuzz-schedule.el ends here
